version: "3"
services:
  bot:
    build: .
    ports:
      - "9229:9229"
    volumes:
      - app-sync:/home/node/app:nocopy
      - var-sync:/home/node/var:nocopy
      - nodemodules:/home/node/app/node_modules
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 bot.js
    environment:
      - LOG_FILE=/home/node/var/log/bot.log
      - DEBUG=true
      - NODE_ENV=development

volumes:
  nodemodules:
  app-sync:
    external: true
  var-sync:
    external: true