FROM node:8.10

RUN npm install serverless -g --unsafe-perm

USER node

RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY ./src/package*.json ./
ENV NODE_ENV=development
RUN npm install

COPY ./src/ ./