service: nodejsapp
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
functions:
  ping:
    handler: webhook.ping
    events:
      - http: GET ping
  reply:
    handler: webhook.reply
    events:
      - http: POST reply
    environment:
      SLACK_API_TOKEN: ${file(./config/aws.${self:provider.stage}.json):SLACK_API_TOKEN}
      LOG_LEVEL: ${file(./config/aws.${self:provider.stage}.json):LOG_LEVEL}
      REDMINE_API_KEY: ${file(./config/aws.${self:provider.stage}.json):REDMINE_API_KEY}
      REDMINE_URL: ${file(./config/aws.${self:provider.stage}.json):REDMINE_URL}
      DEBUG: ${file(./config/aws.${self:provider.stage}.json):DEBUG}