service: nodejsapp
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${env:CI_BRANCH, 'dev'}
functions:
  ping:
    handler: webhook.ping
    events:
      - http: GET ping
  reply:
    handler: webhook.reply
    events:
      - http: POST reply
    environment:
      SLACK_API_TOKEN: ${env:SLACK_API_TOKEN}
      LOG_LEVEL: ${env:LOG_LEVEL}
      REDMINE_API_KEY: ${env:REDMINE_API_KEY}
      REDMINE_URL: ${env:REDMINE_URL}
      DEBUG: ${env:DEBUG}